dfiles]

diff --git a/packages/bookworm-devcontainer/Dockerfile b/packages/bookworm-devcontainer/Dockerfile
--- a/packages/bookworm-devcontainer/Dockerfile
+++ b/packages/bookworm-devcontainer/Dockerfile
@@ -1,106 +1,107 @@
 # syntax=docker/dockerfile:1.5.2
 
+# Stage 1: Node builder for Cypress
 FROM node:alpine as node-builder
-ADD https://raw.githubusercontent.com/zerdos/spike.land/main/.yarn/releases/yarn-4.2.2.cjs /usr/local/bin/yarn
 
+# Add yarn
+ADD https://raw.githubusercontent.com/zerdos/spike.land/main/.yarn/releases/yarn-4.2.2.cjs /usr/local/bin/yarn
 RUN chmod 755 /usr/local/bin/yarn && apk add --no-cache git unzip
 
-# RUN cd && mkdir cy && cd cy && yarn init  && yarn add --dev cypress --mode=skip-build && yarn run cypress install --force
+# Uncomment the following lines if you need to install Cypress during the build
+# RUN mkdir /cy && cd /cy && yarn init -y \
+#     && yarn add --dev cypress --mode=skip-build \
+#     && yarn run cypress install --force
 
+# Stage 2: Base image setup
 FROM debian:bookworm as devimage
 
-### base.Dockerfile
-### Generator: https://github.com/zerdos/spike.land/tree/main/packages
-
-LABEL maintainer=zoltan.erdos@me.com
-
+# Base metadata
+LABEL maintainer="zoltan.erdos@me.com"
 ENV DEBIAN_FRONTEND=noninteractive
 
-## cypress.Dockerfile
-ENV  QT_X11_NO_MITSHM=1 \
-  _X11_NO_MITSHM=1 \
-  _MITSHM=0 
+# Cypress environment variables
+ENV QT_X11_NO_MITSHM=1 \
+    _X11_NO_MITSHM=1 \
+    _MITSHM=0 
 
-
+# Switch to root user
 USER 0
 
+# Update and install base packages
 RUN apt-get update \
-  && apt-get dist-upgrade -y \
-  && apt-get install --no-install-recommends -y \
-  apt-transport-https \
-  apt-utils \
-  curl \
-  git \
-  gpg \
-    libgtk2.0-0 \
-  libgtk-3-0 \
-  libnotify-dev \
-  libgbm-dev \
-  libnss3 \
-  libxss1 \
-  bzip2 \
-  unzip \
-  bzip2 \
-  libasound2 \
-  libxtst6 \
-  xvfb \
-  fonts-liberation \
-  libcurl4 \
-  libappindicator3-1\
-  libcurl3-gnutls \
-  libcurl3-nss \
-  xdg-utils \
-  wget \
-  gpg-agent \
-  htop \
-  inotify-tools \
-  libvips \
-  locales \
-  make \
-  mc \
-  dirmngr \
-  procps \
-  psmisc \
-  software-properties-common \
-  sudo \
-  tzdata \
-  xz-utils \
-  && apt-get install --install-recommends -y \
-  autocutsel \
-  dbus \
-  dbus-x11 \
-  xfwm4 \
-  zsh \
-  fonts-noto-color-emoji \
-  # xvfb \
-  novnc \
-  g++ \
-  # websockify \
-  tigervnc-standalone-server \
-  tigervnc-xorg-extension \
-  && apt-get autoremove -y \
-  && apt-get clean -y \
-  && rm -rf /var/lib/apt/lists/* 
+    && apt-get dist-upgrade -y \
+    && apt-get install --no-install-recommends -y \
+       apt-transport-https \
+       apt-utils \
+       curl \
+       git \
+       gpg \
+       libgtk2.0-0 \
+       libgtk-3-0 \
+       libnotify-dev \
+       libgbm-dev \
+       libnss3 \
+       libxss1 \
+       bzip2 \
+       unzip \
+       libasound2 \
+       libxtst6 \
+       xvfb \
+       fonts-liberation \
+       libcurl4 \
+       libappindicator3-1 \
+       libcurl3-gnutls \
+       libcurl3-nss \
+       xdg-utils \
+       wget \
+       gpg-agent \
+       htop \
+       inotify-tools \
+       libvips \
+       locales \
+       make \
+       mc \
+       dirmngr \
+       procps \
+       psmisc \
+       software-properties-common \
+       sudo \
+       tzdata \
+       xz-utils \
+    && apt-get install --install-recommends -y \
+       autocutsel \
+       dbus \
+       dbus-x11 \
+       xfwm4 \
+       zsh \
+       fonts-noto-color-emoji \
+       novnc \
+       g++ \
+       tigervnc-standalone-server \
+       tigervnc-xorg-extension \
+    && apt-get autoremove -y \
+    && apt-get clean -y \
+    && rm -rf /var/lib/apt/lists/* 
 
+# Define the user and set up sudo permissions
 ARG USER="gitpod"
 ENV USER=${USER}
 
-RUN (addgroup --gid 1001 ${USER}  \
-  && adduser --uid 1001 --disabled-password --gecos "" --force-badname --shell /usr/bin/zsh --ingroup ${USER} ${USER}  || echo user_exist) \
-  && adduser ${USER} sudo \
-  && chown ${USER}:${USER} -R /home/${USER} \
-  && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers \
-  && echo "Set disable_coredump false" >> /etc/sudo.conf \
-  && touch /usr/bin/startx /usr/bin/startWithBash \
-  && chmod +x /usr/bin/startx /usr/bin/startWithBash \
-  && echo "(sudo sysctl fs.inotify.max_user_watches=524288 fs.inotify.max_user_instances=524288 net.core.somaxconn=524288 fscache.object_max_active=524288 || echo failed) && (sudo sysctl -p || echo failed) && (sudo chown ${USER}:${USER} /home/${USER}/tmpfs)" >> /usr/bin/startx \
-  && echo "bash /usr/bin/startx" >> /usr/bin/startWithBash && chmod +x /usr/bin/startWithBash  \
-  # && curl --silent --location https://deb.nodesource.com/setup_18.x | bash - \
-  # && apt-get update \
-  # && apt-get install --no-install-recommends -y nodejs build-essential \
-  #   && apt-get autoremove -y \
-  && apt-get clean -y \
-  && rm -rf /var/lib/apt/lists/* 
+RUN addgroup --gid 1001 ${USER} \
+    && adduser --uid 1001 --disabled-password --gecos "" --force-badname --shell /usr/bin/zsh --ingroup ${USER} ${USER} \
+    && adduser ${USER} sudo \
+    && chown ${USER}:${USER} -R /home/${USER} \
+    && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers \
+    && echo "Set disable_coredump false" >> /etc/sudo.conf
+
+# Set up start scripts
+RUN touch /usr/bin/startx /usr/bin/startWithBash \
+    && chmod +x /usr/bin/startx /usr/bin/startWithBash \
+    && echo "(sudo sysctl fs.inotify.max_user_watches=524288 fs.inotify.max_user_instances=524288 net.core.somaxconn=524288 fscache.object_max_active=524288 || echo failed) && (sudo sysctl -p || echo failed) && (sudo chown ${USER}:${USER} /home/${USER}/tmpfs)" >> /usr/bin/startx \
+    && echo "bash /usr/bin/startx" >> /usr/bin/startWithBash \
+    && chmod +x /usr/bin/startWithBash \
+    && apt-get clean -y \
+    && rm -rf /var/lib/apt/lists/*
 
 
 
@@ -154,21 +155,35 @@ RUN chmod 755 /usr/local/bin/yarn &&   yarn --version
 #   && npm i -g npm yarn
 ### noVNC.Dockerfile
 
+# Set environment variable for the port
 ENV PORT=6080
 
-RUN  git clone https://github.com/novnc/noVNC.git  --depth=1 \
-  && cp -af ./noVNC/.  /usr/share/novnc/ \
-  && rm -rf ./noVNC \
-  && cp /usr/share/novnc/vnc.html /usr/share/novnc/index.html \
-  && (sed -i -e '1 aautocutsel -fork' /etc/X11/Xvnc-session \
-  && sed -i -e 's/iconic/nowin/g' /etc/X11/Xvnc-session \
-  && sed -i -e '1 aterminator &' /etc/X11/Xvnc-session) \
-  || ( sed -i -e '1 aautocutsel -fork' /etc/X11/Xtigervnc-session \
-  && sed -i -e 's/iconic/nowin/g' /etc/X11/Xtigervnc-session \
-  && sed -i -e '1 aterminator &' /etc/X11/Xtigervnc-session ) \
-  && sed -i -e 's/workspace_count=4/workspace_count=1/g' /usr/share/xfwm4/defaults \
-  && sed -i -e 's/use_compositing=true/use_compositing=false/g' /usr/share/xfwm4/defaults \
-  && echo "((chmod 644 ~/.ssh/*.pub && chmod 600 ~/.ssh/id_rsa && chmod 600 ~/.gitconfig) || true ) && (vncserver -SecurityTypes none -cleanstale -useold :1 -localhost no --I-KNOW-THIS-IS-INSECURE && websockify --web=/usr/share/novnc/ --wrap-mode=ignore ${PORT} localhost:5901 || echo ok)" >> /usr/bin/startx
+# Clone the noVNC repository and set up the necessary files
+RUN git clone https://github.com/novnc/noVNC.git --depth=1 \
+    && cp -af ./noVNC/. /usr/share/novnc/ \
+    && rm -rf ./noVNC \
+    && cp /usr/share/novnc/vnc.html /usr/share/novnc/index.html
+
+# Modify Xvnc-session and Xtigervnc-session configuration
+RUN if [ -f /etc/X11/Xvnc-session ]; then \
+        sed -i -e '1 aautocutsel -fork' /etc/X11/Xvnc-session \
+        && sed -i -e 's/iconic/nowin/g' /etc/X11/Xvnc-session \
+        && sed -i -e '1 aterminator &' /etc/X11/Xvnc-session; \
+    else \
+        sed -i -e '1 aautocutsel -fork' /etc/X11/Xtigervnc-session \
+        && sed -i -e 's/iconic/nowin/g' /etc/X11/Xtigervnc-session \
+        && sed -i -e '1 aterminator &' /etc/X11/Xtigervnc-session; \
+    fi
+
+# Adjust xfwm4 defaults
+RUN sed -i -e 's/workspace_count=4/workspace_count=1/g' /usr/share/xfwm4/defaults \
+    && sed -i -e 's/use_compositing=true/use_compositing=false/g' /usr/share/xfwm4/defaults
+
+# Update the startx script
+RUN echo "((chmod 644 ~/.ssh/*.pub && chmod 600 ~/.ssh/id_rsa && chmod 600 ~/.gitconfig) || true ) \
+    && (vncserver -SecurityTypes none -cleanstale -useold :1 -localhost no --I-KNOW-THIS-IS-INSECURE \
+    && websockify --web=/usr/share/novnc/ --wrap-mode=ignore ${PORT} localhost:5901 || echo ok)" \
+    >> /usr/bin/startx
 
 ### xfce.Dockerfile
 
@@ -185,15 +200,25 @@ RUN apt-get update \
 
     
 ### chromium.Dockerfile
-RUN  ( apt-get install -y wget && wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && apt-get install -y ./google-chrome-stable_current_amd64.deb) \
-    ||  (apt-get install -y chromium ||  echo "this arch is not supported") \
-     && apt-get autoremove -y \
-  && apt-get clean -y \
-  && rm -rf /var/lib/apt/lists/* 
-  
+# Update the package list
+RUN apt-get update && \
+    apt-get install -y wget gnupg && \
+    # Try installing Google Chrome
+    (wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
+    apt-get install -y ./google-chrome-stable_current_amd64.deb) || \
+    # If that fails, try installing Chromium
+    (apt-get install -y chromium || \
+    echo "This architecture is not supported for Google Chrome or Chromium.") && \
+    # Clean up
+    apt-get autoremove -y && \
+    apt-get clean -y && \
+    rm -rf /var/lib/apt/lists/* /   -chrome-stable_current_amd64.deb
+
+# Set environment variables
 ENV QT_X11_NO_MITSHM=1
 ENV _X11_NO_MITSHM=1
 ENV _MITSHM=0
+
 ### vscode.Dockerfile
 RUN  (curl -sSL https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
     && echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" >> /etc/apt/sources.list.d/vscode.list \
@@ -202,23 +227,35 @@ RUN  (curl -sSL https://packages.microsoft.com/keys/microsoft.asc | apt-key add 
   && apt-get clean -y \
   && rm -rf /var/lib/apt/lists/* ) || echo "this arch is not supported" 
 #   && sed -i -e 's/\/usr\/bin\/code/\/usr\/share\/code\/code --user-data-dir /g' /usr/share/applications/code.desktop 
-### zsh.Dockerfie
+### zsh.Dockerfile
 
+# Switch to root user to perform the chown operation
 USER 0
+
+# Change ownership of the user's home directory
 RUN chown ${USER}:${USER} -R /home/${USER}
+
+# Switch back to the specified user
 USER ${USER}
 
+# Set the working directory
 WORKDIR /home/${USER}
-RUN cd && rm -rf /home/${USER}/.oh-my-zsh && sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.3/zsh-in-docker.sh)" -- \
--t robbyrussell \
--p git \
--p gitfast \
--p git-extras \
--p yarn \
--a 'CASE_SENSITIVE="true"' \
- && touch  ~/.bashrc && echo ":)" >  ~/.mood
 
+# Install Oh My Zsh with specified plugins and theme
+RUN rm -rf /home/${USER}/.oh-my-zsh \
+    && sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.3/zsh-in-docker.sh)" -- \
+       -t robbyrussell \
+       -p git \
+       -p gitfast \
+       -p git-extras \
+       -p yarn \
+       -a 'CASE_SENSITIVE="true"' \
+    && touch ~/.bashrc \
+    && echo ":)" > ~/.mood
+
+# Set the default shell to zsh
 ENV SHELL=/usr/bin/zsh
+
 ### deno.Dockerfile
 
 USER ${USER}
